# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UIKonf
email: questions@uikonf.com
description: UIKonf is an independent conference in Berlin for serious iOS developers. The last four years were a blast. Let's all celebrate the fifth UIKonf in 2017!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.uikonf.com" # the base hostname & protocol for your site
twitter_username: uikonf
github_username:  uikonf
cfp_enabled: false # switch to 'true' when cfp is active
cfp_url: http://cfp.uikonf.com
tickets_enabled: true # switch to 'true' when ticket are sold
ticket_url: https://ti.to/uikonf/uikonf-2020
ticket_widget_id: uikonf/uikonf-2020

# Gems
plugins:
  - jekyll-redirect-from
  - jekyll-paginate

# Exclude files from the Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  - speakers
  - events
  - days
  - workshops
  - sponsors
  - ambassadors
  - uikonf-2017
  - uikonf-2019

# Build settings
markdown: kramdown

# Author details
authors:
  ekurutepe:
    name: Engin Kurutepe
    twitter: http://twitter.com/ekurutepe
    thumbImg: authors/Engin.jpg
  basine:
    name: Sabine Geithner
    twitter: http://twitter.com/sabinegeithner
    thumbImg: authors/sabine.jpg
  mzaks:
    name: Maxim Zaks
    twitter: https://twitter.com/icex33
    thumbImg: authors/Maxim.jpg
  julia:
    name: Julia Kallenberg
    twitter: https://twitter.com/kallenbergjulia
    thumbImg: authors/julia-kallenberg.jpg
  chriseidhof:
    name: Chris Eidhof
    twitter: https://twitter.com/chriseidhof
    thumbImg: authors/chris_thumb.jpg